#%RAML 1.0 DataType
type: object
properties:
      nomCompte:
        type: string
        required: true
      nom:
        type: string
        required: true
      prenom:
        type: string
        required: true
      sexe:
        type: string
        required: true
      age:
        type: integer
        required: true
      telephone:
        type: string
        required: true
      email:
        type: string
        required: true
      contactPref:
        type: string
        required: true
      categorieProduit:
        type: string[]
        required: true
      produitFavoris:
        type: string
        required: true
      marquePreferee:
        type: string
        required: true
      username:
        type: string
        required: true
      password:
        type: string
        required: true
      confirmPassword:
        type: string
        required: true
