#%RAML 1.0 NamedExample
    value:
        nomCompte: "MonCompte123"
        nom: "Dupont"
        prenom: "Jean"
        sexe: "homme"
        age: 30
        telephone: "+33123456789"
        email: "jean.dupont@example.com"
        contactPref: "email"
        categorieProduit: ["maquillage", "sac"]
        produitFavoris: ["Rouge à lèvres", "Mascara"]
        marquePreferee: ["Chanel", "Dior"]
        username: "jean.dupont@example.com"
        password: "MotDePasse123"
        confirmPassword: "MotDePasse123"
