#%RAML 1.0
title: e-com-proc-api
types:
  productType: !include data-Type/ProductType.raml
  orderType: !include data-Type/OrderType.raml
  compteType: !include data-Type/CompteType.raml
  verifType: !include data-Type/VerifType.raml
/products:
  get:
    
    responses:
      200:
        body:
          application/json:
            type: productType[]
            example: !include example/ProductExample.raml

/orders:
  post:  
    body:
      application/json:
        type: orderType  
        example: !include example/OrderExample.raml  
        
    responses:
      201:
        body:
          application/json: 
            example:
              message: Commande créée avec succès
/compte:
  post:  
    body:
      application/json:
        type: compteType  
        example: !include example/CompteExample.raml  
        
    responses:
      201:
        body:
          application/json: 
            example:
              message: Compte créée avec succès
  get:
    
    queryParameters:
       username:
        type: string
        required: true
       password:
        type: string
        required: true           
    responses:
      200:
        body:
          application/json:
            type: verifType
            example: !include example/VerifExample.raml              